# Generated by Django 2.2.26 on 2022-03-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0002_auto_20220305_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='acountNo',
            new_name='accountNo',
        ),
    ]
