# Generated by Django 2.2.26 on 2022-03-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0004_auto_20220305_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='tariff',
            new_name='deviceNo',
        ),
    ]
